### ISSUE TITLE
Bounty: Streaming function calls

### ISSUE THREAD

**Issue by jxnl** [jxnl/openai_function_call#31]
To be considered checkout : https://replit.com/bounties/@jxnl/streaming-json-parse

I'd like to have the capability of parsing functions calls as they stream out for MultiTask when doing streaming function calls. You can use any existing python library. Must work for nested and deep objects.

Below is some code that won't work, since theres no good way of doing this:

```python
from pydantic import BaseModel

class Task(BaseModel):
    id: int
    title: str

# This is your existing generator that yields chunks of JSON string
def json_chunks(json_string):
    for i in range(0, len(json_string), 5):  # replace 5 with the chunk size you want
         chunk = json_string[i:i+5]
         print("yield chunk:", chunk)
         yield chunk

def tasks_from_chunks(json_chunks: Generator[str, None, None]):
     # do something to get a single task_json
     task = Task.parse_raw(**task_json)
     print("yield task", task)
     yield task
     
json_string = '{"tasks":[{"id":1,"title":"task1"},{"id":2,"title":"task2"},{"id":3,"title":"task3"}]}'

for task in tasks_from_chunks(json_chunks(json_string)):
     print(task)
```

## Success criteria

1) tasks are yielded  as soon as they are parsed, there for task 1 should yield before all jsons chunks are yielded
2) must contain a few examples to show it works correctly.

**Comment by prashantdwivedi** [comment]
Below code; please try it

```python
from pydantic import BaseModel
from typing import Generator
import json

class Task(BaseModel):
    id: int
    title: str

# This is your existing generator that yields chunks of JSON string
def json_chunks(json_string):
    for i in range(0, len(json_string), 5):  # replace 5 with the chunk size you want
        chunk = json_string[i:i+5]
        print("yield chunk:", chunk)
        yield chunk

def tasks_from_chunks(json_chunks: Generator[str, None, None]):
    decoder = json.JSONDecoder()
    buffer = ""

    for chunk in json_chunks:
        buffer += chunk
        try:
            while buffer:
                task_json, index = decoder.raw_decode(buffer)
                if "tasks" in task_json:
                    for task in task_json["tasks"]:
                        task_obj = Task(**task)
                        print("yield task", task_obj)
                        yield task_obj
                buffer = buffer[index:].lstrip()
        except ValueError:
            # Not enough data to decode, keep buffering
            continue

json_string = '{"tasks":[{"id":1,"title":"task1"},{"id":2,"title":"task2"},{"id":3,"title":"task3"}]}'

for task in tasks_from_chunks(json_chunks(json_string)):
    print(task)
```

**Comment by gmako6** [comment]
To address the problem of streaming chunked JSON and returning each item as they are streamed, you can modify the `tasks_from_chunks` function to parse the JSON chunks and yield individual tasks. Here's an updated implementation using the `json` module to parse the JSON and `yield` each task:

```python
import json
from pydantic import BaseModel
from typing import Generator

class Task(BaseModel):
    id: int
    title: str

def json_chunks(json_string):
    for i in range(0, len(json_string), 5):  # replace 5 with the chunk size you want
        chunk = json_string[i:i+5]
        yield chunk

def tasks_from_chunks(json_chunks: Generator[str, None, None]):
    buffer = ""
    for chunk in json_chunks:
        buffer += chunk
        try:
            json_data = json.loads(buffer)
            tasks = json_data.get("tasks", [])
            for task_json in tasks:
                task = Task.parse_obj(task_json)
                yield task
            buffer = ""
        except json.JSONDecodeError:
            # In case the chunk is not a complete JSON object, continue buffering
            pass

json_string = '{"tasks":[{"id":1,"title":"task1"},{"id":2,"title":"task2"},{"id":3,"title":"task3"}]}'

for task in tasks_from_chunks(json_chunks(json_string)):
    print(task)
```

In this updated code, the `tasks_from_chunks` function uses a buffer to accumulate the JSON chunks until a complete JSON object can be parsed. It attempts to load the buffer as JSON, extracts the tasks if available, and yields each task one by one. If there's any incomplete JSON in the buffer, it continues buffering until a complete object is formed.

This implementation should handle streaming JSON chunks and yield each task as they are parsed from the chunks.

**Comment by vikasgola** [comment]
Hi @jxnl.
If I have understood clearly, this is how `tasks_from_chunks` function should work:

As 'tasks_from_chunks' receives chunks till `{"tasks":[{"id":1,"title":"task1"},` (35 chars i.e. divisible by chunk size( here it is 5)). 
Because it contains a json object of task, it should yield a Task object and continue processing further thunks and do same for the future chunks.

**Comment by jxnl** [comment]
Has to work for arbitrary lists

> Hi @jxnl.
> 
> If I have understood clearly, this is how `tasks_from_chunks` function should work:
> 
> 
> 
> As 'tasks_from_chunks' receives chunks till `{"tasks":[{"id":1,"title":"task1"},` (35 chars i.e. divisible by chunk size( here it is 5)). 
> 
> Because it contains a json object of task, it should yield a Task object and continue processing further thunks and do same for the future chunks.

**Comment by jxnl** [comment]
Both solutions load all items before yeilding. I want it to yield befor streaming

**Comment by gmako6** [comment]
If you want to yield tasks before loading all items, you can modify the code as follows:

```python
import json
from pydantic import BaseModel
from typing import Generator

class Task(BaseModel):
    id: int
    title: str

def json_chunks(json_string):
    for i in range(0, len(json_string), 5):  # replace 5 with the chunk size you want
        chunk = json_string[i:i+5]
        yield chunk

def tasks_from_chunks(json_chunks: Generator[str, None, None]):
    buffer = ""
    for chunk in json_chunks:
        buffer += chunk
        while True:
            start_index = buffer.find('{')
            end_index = buffer.find('}')
            if start_index != -1 and end_index != -1:
                json_str = buffer[start_index:end_index+1]
                buffer = buffer[end_index+1:]
                try:
                    task_json = json.loads(json_str)
                    task = Task.parse_obj(task_json)
                    yield task
                except json.JSONDecodeError:
                    # In case the JSON is invalid, skip this task
                    pass
            else:
                break

json_string = '{"tasks":[{"id":1,"title":"task1"},{"id":2,"title":"task2"},{"id":3,"title":"task3"}]}'

for task in tasks_from_chunks(json_chunks(json_string)):
    print(task)
```

In this updated code, the `tasks_from_chunks` function uses a `while` loop to continuously search for complete JSON objects in the buffer. It looks for the first occurrence of '{' and '}' to determine the boundaries of a JSON object. If a complete JSON object is found, it is parsed and yielded as a task. The corresponding substring is removed from the buffer, and the process continues until no more complete objects can be found in the current buffer.

This modification allows tasks to be yielded as soon as complete JSON objects are available in the stream, without waiting for all items to be loaded.

**Comment by godfreykaris** [comment]
This solution yields before streaming:
```python
from pydantic import BaseModel
from typing import Generator
import json


class Task(BaseModel):
  id: int
  title: str


def json_chunks(json_string):
  #We split by a reasonable chunk size.
  chunk_size = 5  # You can adjust this value depending on your actual use case.
  for i in range(0, len(json_string), chunk_size):
    chunk = json_string[i:i + chunk_size]
    yield chunk


def tasks_from_chunks(json_chunks: Generator[str, None, None]):
  # Initialize an empty string to hold the JSON chunks that need to be parsed.
  remaining = ""

  for chunk in json_chunks:
    # Combine the remaining chunk from the previous iteration with the current chunk.
    combined_chunk = remaining + chunk
    try:
      # Try to load the combined JSON string.
      parsed_json = json.loads(combined_chunk)
      remaining = ""  # If successful, reset the remaining string.
    except json.JSONDecodeError:
      # If the JSON is not complete, set the remaining chunk and continue to the next iteration.
      remaining = combined_chunk
      continue

    tasks = parsed_json.get('tasks', [])
    for task_json in tasks:
      # Parse the individual task and yield it.
      task = Task(**task_json)
      print("yield task", task)
      yield task

    # If there is a remaining fragment that couldn't be parsed in this chunk,
    # yield any tasks from it as well (it might be the last task).
    if remaining:
      try:
        parsed_json = json.loads(remaining)
        tasks = parsed_json.get('tasks', [])
        for task_json in tasks:
          task = Task(**task_json)
          yield task
        remaining = ""  # Reset remaining fragment after parsing the last task.
      except json.JSONDecodeError:
        # The remaining fragment is still incomplete, so we'll keep it for the next chunk.
        pass


json_string = '{"tasks":[{"id":1,"title":"task1"},{"id":2,"title":"task2"},{"id":3,"title":"task3"}]}'

# Test case 1: Iterate over the tasks and print them
print("Test case 1:")
for task in tasks_from_chunks(json_chunks(json_string)):
  print(task)

# Test case 2: Collect tasks in a list and print the list
print("\nTest case 2:")
tasks_list = list(tasks_from_chunks(json_chunks(json_string)))
print(tasks_list)

```

**Comment by vikasgola** [comment]
> Both solutions load all items before yeilding. I want it to yield befor streaming

Right. That is what I meant in my first comment.
Here is much cleaner solution to do so for arbitrary chunk size with arbitrary nested and deep objects. 

```python
from pydantic import BaseModel

CHUNK_SIZE = 10
json_string = '{"tasks":[{"id":1,"title":"task1", "test": []},{"id":2,"title":"task2", "test": {"test1": 23, "title": [{"id": 1}]}},{"id":3,"title":"task3"}]}'


class Task(BaseModel):
  id: int
  title: str

def json_chunks(json_string):
  for i in range(0, len(json_string), CHUNK_SIZE):
    chunk = json_string[i:i + CHUNK_SIZE]
    yield chunk

def get_object(str, stack):
  for i, c in enumerate(str):
    if c == "{": stack += 1
    if c == "}":
      stack -= 1
      if stack == 0:
        return str[:i + 1], str[i + 2:]
  return None, str

def tasks_from_chunks(json_chunks):
  started = False
  potential_object = ""
  for chunk in json_chunks:
    potential_object += chunk
    if not started:
      if "[" in chunk:
        started = True
        potential_object = chunk[chunk.find("[") + 1:]
      continue

    task_json, potential_object = get_object(potential_object, 0)
    if task_json:
      print("JSON => ", task_json)
      task = Task.parse_raw(task_json)
      yield task

for task in tasks_from_chunks(json_chunks(json_string)):
  print(task)
  print()
```

**Comment by vikasgola** [comment]
@jxnl for more examples and tests please check this: https://replit.com/@VikasGola/openaifunctioncallissue31#main.py

**Comment by jxnl** [comment]
When I run this it does not yield the first task 

> This solution yields before streaming:
> 
> ```python
> 
> from pydantic import BaseModel
> 
> from typing import Generator
> 
> import json
> 
> 
> 
> 
> 
> class Task(BaseModel):
> 
>   id: int
> 
>   title: str
> 
> 
> 
> 
> 
> def json_chunks(json_string):
> 
>   #We split by a reasonable chunk size.
> 
>   chunk_size = 5  # You can adjust this value depending on your actual use case.
> 
>   for i in range(0, len(json_string), chunk_size):
> 
>     chunk = json_string[i:i + chunk_size]
> 
>     yield chunk
> 
> 
> 
> 
> 
> def tasks_from_chunks(json_chunks: Generator[str, None, None]):
> 
>   # Initialize an empty string to hold the JSON chunks that need to be parsed.
> 
>   remaining = ""
> 
> 
> 
>   for chunk in json_chunks:
> 
>     # Combine the remaining chunk from the previous iteration with the current chunk.
> 
>     combined_chunk = remaining + chunk
> 
>     try:
> 
>       # Try to load the combined JSON string.
> 
>       parsed_json = json.loads(combined_chunk)
> 
>       remaining = ""  # If successful, reset the remaining string.
> 
>     except json.JSONDecodeError:
> 
>       # If the JSON is not complete, set the remaining chunk and continue to the next iteration.
> 
>       remaining = combined_chunk
> 
>       continue
> 
> 
> 
>     tasks = parsed_json.get('tasks', [])
> 
>     for task_json in tasks:
> 
>       # Parse the individual task and yield it.
> 
>       task = Task(**task_json)
> 
>       print("yield task", task)
> 
>       yield task
> 
> 
> 
>     # If there is a remaining fragment that couldn't be parsed in this chunk,
> 
>     # yield any tasks from it as well (it might be the last task).
> 
>     if remaining:
> 
>       try:
> 
>         parsed_json = json.loads(remaining)
> 
>         tasks = parsed_json.get('tasks', [])
> 
>         for task_json in tasks:
> 
>           task = Task(**task_json)
> 
>           yield task
> 
>         remaining = ""  # Reset remaining fragment after parsing the last task.
> 
>       except json.JSONDecodeError:
> 
>         # The remaining fragment is still incomplete, so we'll keep it for the next chunk.
> 
>         pass
> 
> 
> 
> 
> 
> json_string = '{"tasks":[{"id":1,"title":"task1"},{"id":2,"title":"task2"},{"id":3,"title":"task3"}]}'
> 
> 
> 
> # Test case 1: Iterate over the tasks and print them
> 
> print("Test case 1:")
> 
> for task in tasks_from_chunks(json_chunks(json_string)):
> 
>   print(task)
> 
> 
> 
> # Test case 2: Collect tasks in a list and print the list
> 
> print("\nTest case 2:")
> 
> tasks_list = list(tasks_from_chunks(json_chunks(json_string)))
> 
> print(tasks_list)
> 
> 
> 
> ```

**Comment by jxnl** [comment]
None of these work. Add the print statement back in the json chunkier and you'll see that all the chunks print before any tasks.

**Comment by jxnl** [comment]
Don't remove the print chunk line, if the tasks are only printed after all the chunks are yields. It does not meet the success condition.
