### ISSUE TITLE
OpenDNS considers onrender.com a security threat

### ISSUE THREAD

**Issue by oaustegard** [jxnl/openai_function_call#54]
re tweet at https://twitter.com/jxnlco/status/1677907692122259456?s=20

A number of people on Cisco-administered networks may see some version of this error when attempting to access:

### openai-function-call.onrender.com is classified as a potential security risk and access is restricted

May want to publish to a different domain/github pages?

**Comment by jxnl** [comment]
oh shoot will work that out

**Comment by jxnl** [comment]
@oaustegard got it up on https://jxnl.github.io/openai_function_call/ as well. will figure out redirects and naming
