### ISSUE TITLE
create func of ChatCompletion does not return completion if self.function is None

### ISSUE THREAD

**Issue by Phodaie** [jxnl/openai_function_call#55]
in dsl/completion.py shouldn't create return completion?

def create(self):
        """
        Create a chat response from the OpenAI API

        Returns:
            response (OpenAISchema): The response from the OpenAI API
        """
        kwargs = self.kwargs
        completion = openai.ChatCompletion.create(**kwargs)
        if self.function:
            return self.function.from_response(completion)
       **return completion**

**Comment by jxnl** [comment]
thats a mistake, mind making a PR will fix later otherwise
